---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-system
  labels:
    app: grafana
    group: grafana
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
    group: grafana
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: grafana
  namespace: kube-system
  labels:
    app: grafana
    group: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      group: grafana
  template:
    metadata:
      labels:
        app: grafana
        group: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:master
          imagePullPolicy: Always
          env:
            - name: GF_EXPLORE_ENABLED
              value: "true"
          volumeMounts:
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: datasource
          configMap:
            name: grafana-datasource
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: kube-system
  labels:
    app: grafana
    group: grafana
data:
  loki.yaml: |-
    apiVersion: 1

    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: false
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus
        editable: false



