---
apiVersion: v1
kind: Service
metadata:
  name: grafana-loki-test
  namespace: application
  labels:
    app: grafana-loki-test
    group: loki-test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: grafana-loki-test
    group: loki-test
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: grafana-loki-test
  namespace: application
  labels:
    app: grafana-loki-test
    group: loki-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-loki-test
      group: loki-test
  template:
    metadata:
      labels:
        app: grafana-loki-test
        group: loki-test
    spec:
      containers:
        - name: grafana-loki-test
          image: pnyak/grafana-loki-test:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: grafana-loki-test
  namespace: application
  labels:
    app: grafana-loki-test
    group: loki-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: grafana-loki-test
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
